### ISSUE TITLE
Add pastie Language type

### ISSUE THREAD

**Issue by ovidiuvisan** [simmel/vim-pastie#3]
Maybe add pastie based on file type or specified.

**Comment by simmel** [comment]
The bug was threefold:
* In `filetype.vim` which ships with vim there is an assumption: if a file starts with #-sign it sets ft=conf, which is weird but can be worked around.
* When setting the filetype which will be sent to pastie.org it wasn't urlencoded. And `"c++"` is really `"c  "` when URL decoding is applied.
* There was a regex (`\w`) which only matched words when parsing the "header" and `+` isn't included in `\w`.

Does #5 solve your problems @ovidiuvisan and @timss ?

**Comment by timss** [comment]
@simmel I don't use pastie.org because I disagree with many of the changes that has been introduced over the years, and therefore no longer have the need for vim-pastie.

However, since you have taken upon yourself to maintain this project I did give it a shot. Can't really say I remember how it worked (and when it didn't) back in 2013, but it seems to still have problems with cpp/c++. Python on the other hand works fine.

Instead of setting the syntax or file type on pastie.org, a header is added for C++ files. I just tested with a random file and this is what I got:

http://pastie.org/10214212 (cpp)   
http://pastie.org/10214206 (python)

**Comment by simmel** [comment]
Are you sure @timss that you are using my branch/PR that is in #5?

This is what I got with my branch/PR: http://pastie.org/private/3mw49vwt5xogzbzlbbqdw

**Comment by timss** [comment]
My apologies, @simmel. I thought I saw the pull already merged and therefore incorrectly tested the outdated version. The one in #5 works fine! :)

**Comment by simmel** [comment]
Cool, thanks @timss!
